import type { DamageScenario } from '@/components/3d/DamageDetailViewer'
import { pickGlossary } from '@/lib/content/hail-glossary'

// ════════════════════════════════════════════════════════════════════════════════
// DAMAGE SCENARIOS — JigSpace-style cinematic damage inspection walkthroughs
// Residential hail set is built for independent-adjuster training: each scenario
// runs walkthrough → find-the-damage → scope-sheet builder → terminology drill.
// The non-hail scenarios stay walkthrough-only.
//
// `damageType` + `facing` drive the visible 3D damage marks rendered on the house.
// ════════════════════════════════════════════════════════════════════════════════

// Helper — camera preset shorthand
const C = (p: [number, number, number], t: [number, number, number], fov: number) =>
  ({ position: p, target: t, fov })

// ════════════════════════════════════════════════════════════════════════════════
// RESIDENTIAL HAIL — Scenario 1: Roof
// ════════════════════════════════════════════════════════════════════════════════

export const HAIL_ROOF_RESIDENTIAL: DamageScenario = {
  id: 'hail-roof-residential',
  title: 'Residential Hail: Roof',
  subtitle: 'Scope a hail-damaged composition roof — bruises, soft metals, and the line items they drive',
  visibleGroups: ['sheathing', 'ridge_cap', 'drip_edge', 'soft_metals', 'fascia_soffit', 'gutters', 'chimney', 'gable_ends', 'dormer', 'garage_roof'],
  annotations: [
    {
      id: 'hr-1',
      position: [2, 2.2, 2.3],
      damageType: 'hail-bruise',
      facing: 'roof-front',
      title: 'Shingle bruise (mat fracture)',
      description: 'A soft, round impact point where the fiberglass mat is fractured. Press around it — a true hail bruise gives slightly under finger pressure. This is functional damage: the mat is the shingle’s structural layer. Bruises are consistent in size across the slope, matching the hailstone diameter.',
      severity: 'severe',
      codeRef: 'IRC R905.2',
      indicator: 'circle',
      radius: 0.3,
    },
    {
      id: 'hr-2',
      position: [-3, 1.8, 2.8],
      damageType: 'hail-bruise',
      facing: 'roof-front',
      title: 'Granule loss at impact',
      description: 'Hail granule loss is concentrated in round impact zones, exposing the black asphalt below. Distinguish it from broad, uniform weathering loss. Granules in the gutters support the finding but are not proof on their own — pair granule loss with a fractured mat.',
      severity: 'moderate',
      indicator: 'circle',
      radius: 0.25,
    },
    {
      id: 'hr-3',
      position: [1, 3.74, 0],
      damageType: 'crack',
      facing: 'up',
      title: 'Ridge cap damage',
      description: 'Ridge caps take direct, exposed impact and crack or fracture readily. They are a separate line item from field shingles. Walk and photograph the full ridge — every ridge and hip run.',
      severity: 'moderate',
      indicator: 'circle',
      radius: 0.3,
    },
    {
      id: 'hr-4',
      position: [-2, 3.2, -1],
      damageType: 'dent',
      facing: 'up',
      title: 'Soft metal confirmation',
      description: 'The turbine vent is aluminum and dents from hail unmistakably. Soft metals corroborate hail contact and establish size and direction before you ever debate a shingle bruise. Document soft metals first.',
      severity: 'moderate',
      indicator: 'circle',
      radius: 0.3,
    },
    {
      id: 'hr-5',
      position: [4, 2.0, -1.5],
      damageType: 'hail-bruise',
      facing: 'roof-back',
      title: 'Blister — NOT hail',
      description: 'A raised pock where granules popped off but the mat below is hard and intact. Blisters are random in size and have no soft give. Calling blisters as bruises gets the claim denied and damages your credibility — separate them in your report.',
      severity: 'minor',
      indicator: 'circle',
      radius: 0.2,
    },
    {
      id: 'hr-6',
      position: [-3, 0.6, 5.0],
      damageType: 'dent',
      facing: 'up',
      title: 'Drip edge dents',
      description: 'Drip edge is soft metal along the eaves and rakes. Round dents confirm hail and the drip edge is replaced with the covering. Note material and total linear footage.',
      severity: 'minor',
      indicator: 'circle',
      radius: 0.3,
    },
  ],
  stops: [
    {
      ...C([9, 15, 16], [0, 2.5, 0], 46),
      title: 'Roof Overview',
      narration: 'Start from above the storm-facing slopes. Before you get close, read the whole roof: which slopes face the storm direction, where the ridges and hips run, where the penetrations and soft metals are. These landmarks tell you where to set your test squares.',
      annotationIds: [],
      highlightedGroups: ['sheathing'],
    },
    {
      ...C([-0.5, 7, 12], [-0.5, 2, 2.55], 38),
      title: 'Approach the Field Shingles',
      narration: 'Move onto the front slope. You are looking for round impact points with granule loss and a soft feel. Do not assume everything you see is hail — the most common mistake is calling blisters as bruises. Set a 10×10 test square here and count the hits.',
      annotationIds: ['hr-1', 'hr-2'],
      highlightedGroups: ['sheathing'],
    },
    {
      ...C([2.5, 6.5, 9], [2, 2.2, 2.3], 33),
      title: 'Bruise vs. Blister',
      narration: 'A bruise is soft and the mat below is fractured — functional damage. A blister is raised, random in size, and hard underneath — not hail. Press around each suspect spot. Chalk the test square and photograph the fracture pattern. Bruise sizes are consistent across the slope; blisters are not.',
      annotationIds: ['hr-1', 'hr-5'],
      highlightedGroups: ['sheathing'],
    },
    {
      ...C([-3, 8, -8], [-2, 3.2, -1], 34),
      title: 'Soft Metals Corroborate the Storm',
      narration: 'Document soft metals before you argue a single shingle. The turbine vent, pipe boots, and vent caps are aluminum — they dent clearly and consistently. Round dents that match the storm report cannot be disputed. This evidence chain supports your test squares.',
      annotationIds: ['hr-4'],
      highlightedGroups: ['soft_metals'],
    },
    {
      ...C([3, 8, 9], [1, 3.74, 0], 36),
      title: 'Ridge, Hips, and Edges',
      narration: 'Walk the ridge and hip runs and the eave and rake edges. Ridge caps and drip edge are exposed and take direct impact — each is its own line item, separate from the field shingles. One missed run is one missed line.',
      annotationIds: ['hr-3', 'hr-6'],
      highlightedGroups: ['ridge_cap', 'drip_edge'],
    },
    {
      ...C([10, 13, 15], [0, 2.5, 1], 44),
      title: 'Documentation Standard',
      narration: 'For the scope: chalk-tested test squares on every storm-facing slope, soft metals documented for independent confirmation, ridge and edges photographed separately, blisters labeled as pre-existing, and the roof age and brittleness noted. Separate storm damage from pre-existing or the whole claim loses credibility.',
      annotationIds: ['hr-1', 'hr-2', 'hr-3', 'hr-4', 'hr-5', 'hr-6'],
      highlightedGroups: ['sheathing', 'ridge_cap', 'soft_metals'],
    },
  ],
  findChallenge: {
    prompt: 'Orbit the roof and click each piece of documentable hail damage. Look at the field shingles, the ridge, the soft metals, and the eave edges.',
    startView: { position: [5, 12, 13], target: [0, 2.2, 1], fov: 40 },
    targets: [
      { id: 'fr-bruise', label: 'Shingle bruise (mat fracture)', position: [2, 2.2, 2.3], radius: 1.4, meshGroups: ['sheathing'], severity: 'severe', damageType: 'hail-bruise', facing: 'roof-front', explanation: 'Soft, round, fractured mat — functional damage. Drives full-slope shingle replacement.' },
      { id: 'fr-granule', label: 'Granule loss at impact', position: [-3, 1.8, 2.8], radius: 1.4, meshGroups: ['sheathing'], severity: 'moderate', damageType: 'hail-bruise', facing: 'roof-front', explanation: 'Concentrated round granule loss — pair it with the fractured mat to support the claim.' },
      { id: 'fr-ridge', label: 'Ridge cap damage', position: [1, 3.74, 0], radius: 1.6, meshGroups: ['ridge_cap'], severity: 'moderate', damageType: 'crack', facing: 'up', explanation: 'Ridge caps are a separate line item from field shingles.' },
      { id: 'fr-soft', label: 'Dented turbine vent', position: [-2, 3.2, -1], radius: 1.1, meshGroups: ['soft_metals'], severity: 'moderate', damageType: 'dent', facing: 'up', explanation: 'Soft metal — your independent confirmation of hail contact, size, and direction.' },
      { id: 'fr-dripedge', label: 'Dented drip edge', position: [-3, 0.6, 5.0], radius: 1.6, meshGroups: ['drip_edge'], severity: 'minor', damageType: 'dent', facing: 'up', explanation: 'Drip edge is soft metal along the eaves — replaced with the covering.' },
    ],
  },
  scopeSheet: {
    prompt: 'You documented functional hail damage across the storm-facing slopes. Build the roof scope — select only the line items the inspection supports.',
    items: [
      { id: 'r-shingles', category: 'Roof Covering', label: 'Replace architectural composition shingles — affected slopes', code: 'RFG 240', correct: true, note: 'Functional mat fracture documented across test squares. Like kind and quality replacement of the damaged slopes.' },
      { id: 'r-ridge', category: 'Roof Covering', label: 'Replace ridge cap shingles — all ridge & hip runs', code: 'RFG RIDGC', correct: true, note: 'Ridge caps take direct impact and are a separate line item from field shingles.' },
      { id: 'r-felt', category: 'Roof Covering', label: 'Synthetic underlayment — affected slopes', code: 'RFG SYNFLT', correct: true, note: 'Underlayment is replaced with the covering it sits under.' },
      { id: 'r-iws', category: 'Roof Covering', label: 'Ice & water barrier at eaves — code upgrade', code: 'RFG IWS', correct: true, note: 'Frequently triggered when a slope is replaced, but jurisdiction-dependent — confirm local code adoption before adding.' },
      { id: 'r-dripedge', category: 'Soft Metals', label: 'Replace drip edge — eaves & rakes', code: 'RFG DREDG', correct: true, note: 'Drip edge is soft metal, was impacted, and is replaced with the covering.' },
      { id: 'r-turbine', category: 'Soft Metals', label: 'Replace turbine vent — dented & seized', correct: true, note: 'A dented, seized vent is a replacement, not a repair, and is its own line item.' },
      { id: 'r-dr-gutter', category: 'Soft Metals', label: 'Detach & reset gutters to replace drip edge', correct: true, note: 'D&R — the gutters may be sound but are in the way of the drip edge work.' },
      { id: 'r-decking', category: 'Do Not Include', label: 'Replace roof decking — entire roof', correct: false, note: 'No decking damage was documented. Decking is scoped only where it is actually rotted or broken — never as a default.' },
      { id: 'r-interior', category: 'Do Not Include', label: 'Repaint interior ceilings', correct: false, note: 'No interior water intrusion was documented. Scope only what the inspection supports.' },
      { id: 'r-powerwash', category: 'Do Not Include', label: 'Power wash roof surface', correct: false, note: 'Cleaning is a maintenance item, not hail repair.' },
    ],
  },
  glossary: pickGlossary(
    ['bruise', 'blister', 'soft-metals', 'test-square', 'granule-loss', 'brittleness', 'line-item', 'scope-sheet'],
    'Lock in the terminology behind a defensible hail roof scope.',
  ),
}

// ════════════════════════════════════════════════════════════════════════════════
// RESIDENTIAL HAIL — Scenario 2: Windows & Doors
// ════════════════════════════════════════════════════════════════════════════════

export const HAIL_WINDOWS_DOORS: DamageScenario = {
  id: 'hail-windows-doors',
  title: 'Residential Hail: Windows & Doors',
  subtitle: 'Inspect and scope hail impact on glazing, screens, frames, entry doors, and garage doors',
  visibleGroups: ['walls_1st', 'walls_2nd', 'windows', 'doors', 'stone_wainscot', 'fascia_soffit', 'foundation', 'gable_ends'],
  annotations: [
    {
      id: 'hw-1',
      position: [3, -0.45, 4.6],
      damageType: 'crack',
      facing: 'out',
      title: 'Cracked glazing',
      description: 'Hail fractures window glazing in a starburst or bullseye pattern radiating from a round impact point. Photograph with a ruler at the impact point to document hail diameter. Single-pane and older double-pane units are most susceptible.',
      severity: 'severe',
      codeRef: 'IRC R613.1',
      indicator: 'circle',
      radius: 0.3,
    },
    {
      id: 'hw-2',
      position: [5, -3.2, 4.6],
      damageType: 'dent',
      facing: 'out',
      title: 'Dented window frame',
      description: 'Aluminum window frames show round dents on the exposed face; vinyl frames crack rather than dent; wood frames splinter. Each damaged frame is a separate line item — document material, size, and operation type.',
      severity: 'moderate',
      indicator: 'circle',
      radius: 0.25,
    },
    {
      id: 'hw-3',
      position: [-3, -0.45, 4.6],
      damageType: 'puncture',
      facing: 'out',
      title: 'Damaged screen',
      description: 'Screens are the first indicator of hail at a property — stretched mesh, punctures, bent frames. Each screen is a line item by size. Cheap to replace but valuable as proof of hail direction and size.',
      severity: 'minor',
      indicator: 'circle',
      radius: 0.3,
    },
    {
      id: 'hw-4',
      position: [-5, -3.2, 4.6],
      damageType: 'crack',
      facing: 'out',
      markScale: 0.85,
      title: 'Broken seal (fogged IGU)',
      description: 'A hail strike can break the hermetic seal on an insulated glass unit, fogging the space between panes. This can take days or weeks to appear after the loss. Document fogged units and note the date of loss — the IGU is a separate line item from the sash.',
      severity: 'severe',
      codeRef: 'ASTM E2190',
      indicator: 'circle',
      radius: 0.25,
    },
    {
      id: 'hw-5',
      position: [0, -4.1, 4.58],
      damageType: 'dent',
      facing: 'out',
      title: 'Entry door panel dents',
      description: 'Steel and fiberglass entry doors show round dents on the exposed face from hail. Aluminum storm doors dent readily. Document the door type and whether the dents are repairable or warrant replacement — each is its own line item.',
      severity: 'moderate',
      indicator: 'circle',
      radius: 0.3,
    },
    {
      id: 'hw-6',
      position: [-9.5, -3.9, 3.58],
      damageType: 'dent',
      facing: 'out',
      markScale: 1.3,
      title: 'Garage door panel dents',
      description: 'Steel garage door panels dent in a consistent pattern across the storm-facing face. Document the number of damaged sections — partial-panel replacement is often possible, but matching across sections may drive a full-door replacement.',
      severity: 'moderate',
      indicator: 'circle',
      radius: 0.4,
    },
  ],
  stops: [
    {
      ...C([0, 1, 18], [0, -1.5, 3], 44),
      title: 'Front Elevation Overview',
      narration: 'Start with a full front elevation photo showing every fenestration — windows and doors. This establishes the building face and shows the carrier how many openings are exposed to the storm direction. Count every unit on the storm-facing elevations.',
      annotationIds: [],
      highlightedGroups: ['windows', 'doors'],
    },
    {
      ...C([4, -1.8, 12], [4, -1.8, 4.6], 36),
      title: 'Glazing and Frame',
      narration: 'Inspect each window on the storm-facing elevation. Glazing fractures in a starburst from a round impact point — measure it. Aluminum frames dent, vinyl cracks, wood splinters. The glazing, the frame, and the trim are separate components and separate line items. Do not combine them.',
      annotationIds: ['hw-1', 'hw-2'],
      highlightedGroups: ['windows'],
    },
    {
      ...C([-4, -1.8, 12], [-4, -1.8, 4.6], 36),
      title: 'Screens and Seals',
      narration: 'Screens show hail clearly and prove direction and size. Then check insulated glass units for fogging — a broken seal may not show for days or weeks after the loss, so note the date of loss. Each screen and each fogged IGU is its own line item.',
      annotationIds: ['hw-3', 'hw-4'],
      highlightedGroups: ['windows'],
    },
    {
      ...C([0, -3.5, 11], [0, -4.1, 4.58], 34),
      title: 'Entry Door',
      narration: 'Steel and fiberglass entry doors dent on the exposed face. Storm doors are aluminum and dent readily. Photograph the dents with a ruler and decide repair vs. replacement. The door, the storm door, and the trim are separate line items.',
      annotationIds: ['hw-5'],
      highlightedGroups: ['doors'],
    },
    {
      ...C([-9.5, -2.5, 11], [-9.5, -3.9, 3.58], 38),
      title: 'Garage Door',
      narration: 'Garage door panels dent in a repeating pattern across the storm-facing face. Document how many sections are damaged. Partial replacement is sometimes possible, but matching across sections — and the line-of-sight rule — often drives a full-door replacement.',
      annotationIds: ['hw-6'],
      highlightedGroups: ['doors'],
    },
    {
      ...C([-2, 2, 17], [-2, -2, 3], 46),
      title: 'Complete Documentation',
      narration: 'For the scope sheet: number of damaged units by type and size, the specific damage per unit (glazing, frame, screen, IGU, trim), photos with a ruler for each, and full specifications. One missed opening is one missed line item.',
      annotationIds: ['hw-1', 'hw-2', 'hw-3', 'hw-4', 'hw-5', 'hw-6'],
      highlightedGroups: ['windows', 'doors'],
    },
  ],
  findChallenge: {
    prompt: 'Inspect the storm-facing elevation. Click each documentable piece of hail damage on the windows and doors.',
    startView: { position: [0, -0.5, 16], target: [0, -1.5, 4], fov: 38 },
    targets: [
      { id: 'fw-glazing', label: 'Cracked glazing', position: [3, -0.45, 4.6], radius: 1.1, meshGroups: ['windows'], severity: 'severe', damageType: 'crack', facing: 'out', explanation: 'Starburst fracture from a round impact — the glazing/IGU is its own line item.' },
      { id: 'fw-frame', label: 'Dented window frame', position: [5, -3.2, 4.6], radius: 1.1, meshGroups: ['windows'], severity: 'moderate', damageType: 'dent', facing: 'out', explanation: 'Frame damage is separate from the glazing — document material and size.' },
      { id: 'fw-screen', label: 'Damaged screen', position: [-3, -0.45, 4.6], radius: 1.1, meshGroups: ['windows'], severity: 'minor', damageType: 'puncture', facing: 'out', explanation: 'Screens prove hail direction and size — a line item by screen size.' },
      { id: 'fw-entry', label: 'Entry door dents', position: [0, -4.1, 4.58], radius: 1.2, meshGroups: ['doors'], severity: 'moderate', damageType: 'dent', facing: 'out', explanation: 'Steel/fiberglass doors dent on the exposed face — repair vs. replace is a judgment call.' },
      { id: 'fw-garage', label: 'Garage door panel dents', position: [-9.5, -3.9, 3.58], radius: 1.8, meshGroups: ['doors'], severity: 'moderate', damageType: 'dent', facing: 'out', markScale: 1.3, explanation: 'Document damaged sections — matching may drive a full-door replacement.' },
    ],
  },
  scopeSheet: {
    prompt: 'You documented hail damage to the windows and doors on the storm-facing elevations. Build the scope — select only the supported line items.',
    items: [
      { id: 'w-igu', category: 'Glazing & Sash', label: 'Replace insulated glass unit (IGU) — fogged / seal failure', correct: true, note: 'A broken hermetic seal is functional damage and a separate line item from the sash and frame.' },
      { id: 'w-glazing', category: 'Glazing & Sash', label: 'Replace fractured glazing — by unit size', correct: true, note: 'Starburst fracture documented with a ruler at the impact point.' },
      { id: 'w-frame', category: 'Glazing & Sash', label: 'Replace dented window frame / sash section', correct: true, note: 'Frame damage is documented and is separate from the glazing line item.' },
      { id: 'w-screen', category: 'Screens & Trim', label: 'Replace window screen — by size', correct: true, note: 'Each damaged screen is its own line item and proves hail direction and size.' },
      { id: 'w-trim', category: 'Screens & Trim', label: 'Replace exterior window trim / brick mold', correct: true, note: 'Exterior trim damage is documented and is a separate component from the window unit.' },
      { id: 'w-entry', category: 'Doors', label: 'Replace steel entry door — hail-dented panel', correct: true, note: 'Dents on the exposed face are documented; repair vs. replace is a judgment call supported by photos.' },
      { id: 'w-garage', category: 'Doors', label: 'Replace / repair garage door — damaged sections', correct: true, note: 'Damaged sections documented; matching across sections may extend to a full-door replacement.' },
      { id: 'w-allwindows', category: 'Do Not Include', label: 'Replace every window in the home', correct: false, note: 'Replace only documented damaged units unless a matching statute or line-of-sight limitation extends the scope — and document that limitation first.' },
      { id: 'w-blinds', category: 'Do Not Include', label: 'Replace interior window blinds', correct: false, note: 'No interior damage was documented. Scope only what the inspection supports.' },
      { id: 'w-sills', category: 'Do Not Include', label: 'Repaint undamaged window sills', correct: false, note: 'Painting is only scoped where a damaged component is repaired or replaced.' },
    ],
  },
  glossary: pickGlossary(
    ['igu', 'functional-vs-cosmetic', 'soft-metals', 'detach-reset', 'matching', 'collateral-damage', 'dol', 'line-item'],
    'Lock in the terminology behind a windows-and-doors hail scope.',
  ),
}

// ════════════════════════════════════════════════════════════════════════════════
// RESIDENTIAL HAIL — Scenario 3: Siding & Exterior
// ════════════════════════════════════════════════════════════════════════════════

export const HAIL_SIDING_EXTERIOR: DamageScenario = {
  id: 'hail-siding-exterior',
  title: 'Residential Hail: Siding & Exterior',
  subtitle: 'Document hail on siding, fascia, soffit, and gutters — and the matching question it raises',
  visibleGroups: ['walls_1st', 'walls_2nd', 'gable_ends', 'stone_wainscot', 'fascia_soffit', 'gutters', 'foundation', 'windows', 'doors'],
  annotations: [
    {
      id: 'hs-1',
      position: [4, -0.65, 4.5],
      damageType: 'crack',
      facing: 'out',
      title: 'Cracked vinyl siding',
      description: 'Vinyl siding cracks and chips from hail rather than denting — most visible on cold-weather impacts. Cracks run vertically from the impact point. Each damaged course is documented; matching is the central question with vinyl.',
      severity: 'moderate',
      indicator: 'circle',
      radius: 0.3,
    },
    {
      id: 'hs-2',
      position: [-4, -3.5, 4.5],
      damageType: 'spatter',
      facing: 'out',
      title: 'Hail spatter on siding',
      description: 'Clean round spots where hail knocked oxidation, dirt, or chalking off the surface without cracking it. Spatter confirms the storm and helps size and date the event — but on its own it is not functional damage.',
      severity: 'minor',
      indicator: 'circle',
      radius: 0.3,
    },
    {
      id: 'hs-3',
      position: [3, 0.55, 5.0],
      damageType: 'dent',
      facing: 'out',
      title: 'Dented aluminum fascia',
      description: 'Aluminum fascia dents and can be holed by hail. It is a soft metal — round dents confirm the storm. Fascia is documented by linear foot and is a separate line item from the soffit and gutters.',
      severity: 'moderate',
      indicator: 'circle',
      radius: 0.3,
    },
    {
      id: 'hs-4',
      position: [-3, 0.32, 5.0],
      damageType: 'dent',
      facing: 'out',
      title: 'Gutter dents — top & front face',
      description: 'Hail dents the horizontal top face and the vertical front face of the gutter — historically scoped as separate line items. Document gutter type, material, size, and total linear footage. Downspouts are separate items by size.',
      severity: 'moderate',
      indicator: 'circle',
      radius: 0.3,
    },
    {
      id: 'hs-5',
      position: [10, 1.6, 4],
      damageType: 'crack',
      facing: 'out',
      title: 'Gable end siding',
      description: 'Gable-end siding sits high on the storm-facing elevation and is easily missed from the ground. Inspect it from a ladder or with magnification — damage here is documented the same as wall siding.',
      severity: 'moderate',
      indicator: 'circle',
      radius: 0.35,
    },
    {
      id: 'hs-6',
      position: [-3, 0.42, 4.75],
      damageType: 'puncture',
      facing: 'up',
      title: 'Soffit panel damage',
      description: 'Aluminum and vinyl soffit panels crack or puncture from hail driven at an angle, especially on the windward side. Soffit is a separate line item from fascia — document by panel and run.',
      severity: 'minor',
      indicator: 'circle',
      radius: 0.3,
    },
  ],
  stops: [
    {
      ...C([4, 2, 18], [1, -1, 3], 46),
      title: 'Elevation Overview',
      narration: 'Read the full elevation before you get close. Note which walls face the storm direction and where the siding type changes. Hail damage on siding is directional — a real storm leaves a consistent pattern on one or two elevations.',
      annotationIds: [],
      highlightedGroups: ['walls_1st', 'walls_2nd'],
    },
    {
      ...C([0, -1.5, 15], [0, -2.1, 4.5], 44),
      title: 'Siding — Cracks vs. Spatter',
      narration: 'Vinyl siding cracks rather than dents — cracks run vertically from a round impact point. Spatter is a clean round spot with no crack: it confirms the storm but is not functional damage on its own. Document the difference clearly; carriers scrutinize siding claims.',
      annotationIds: ['hs-1', 'hs-2'],
      highlightedGroups: ['walls_1st', 'walls_2nd'],
    },
    {
      ...C([0, 1.5, 13.5], [0, 0.5, 4.9], 40),
      title: 'Fascia and Soffit',
      narration: 'Aluminum fascia is soft metal — it dents and can be holed. Soffit panels crack or puncture from angled hail on the windward side. Fascia and soffit are separate line items from each other and from the gutters. Document each by linear foot and run.',
      annotationIds: ['hs-3', 'hs-6'],
      highlightedGroups: ['fascia_soffit'],
    },
    {
      ...C([-3, 1.5, 11], [-3, 0.32, 5.0], 36),
      title: 'Gutters and Downspouts',
      narration: 'Hail dents the top face and the front face of the gutter — historically two separate line items. Walk the full run with a ruler. Document type, material, size, and linear footage. Downspouts are separate items by size.',
      annotationIds: ['hs-4'],
      highlightedGroups: ['gutters'],
    },
    {
      ...C([10, 3, 11], [10, 1.6, 4], 36),
      title: 'Gable Ends — Easily Missed',
      narration: 'Gable-end siding sits high and is routinely missed from the ground. Inspect it from a ladder or with magnification. Damage here is documented the same as wall siding — and it is often what triggers the matching question for the whole elevation.',
      annotationIds: ['hs-5'],
      highlightedGroups: ['gable_ends'],
    },
    {
      ...C([5, 3, 17], [1, -1, 3], 46),
      title: 'The Matching Question',
      narration: 'When damaged siding cannot be matched within a continuous line of sight, the scope may extend to the full elevation — but only where the policy and the state matching statute support it. Document the matching limitation with photos before you extend the scope. Build the scope from the inspection, not a template.',
      annotationIds: ['hs-1', 'hs-2', 'hs-3', 'hs-4', 'hs-5', 'hs-6'],
      highlightedGroups: ['walls_1st', 'walls_2nd', 'gable_ends', 'fascia_soffit', 'gutters'],
    },
  ],
  findChallenge: {
    prompt: 'Walk the storm-facing elevations. Click each documentable piece of hail damage on the siding, trim, and drainage.',
    startView: { position: [4, 0, 15], target: [1, -1, 3], fov: 42 },
    targets: [
      { id: 'fs-vinyl', label: 'Cracked vinyl siding', position: [4, -0.65, 4.5], radius: 1.3, meshGroups: ['walls_2nd'], severity: 'moderate', damageType: 'crack', facing: 'out', explanation: 'Vinyl cracks rather than dents — documented by course; matching is the central question.' },
      { id: 'fs-spatter', label: 'Hail spatter on siding', position: [-4, -3.5, 4.5], radius: 1.4, meshGroups: ['walls_1st'], severity: 'minor', damageType: 'spatter', facing: 'out', explanation: 'Confirms and sizes the storm — but spatter alone is not functional damage.' },
      { id: 'fs-fascia', label: 'Dented aluminum fascia', position: [3, 0.55, 5.0], radius: 1.4, meshGroups: ['fascia_soffit'], severity: 'moderate', damageType: 'dent', facing: 'out', explanation: 'Soft metal — round dents confirm the storm; documented by linear foot.' },
      { id: 'fs-gutter', label: 'Gutter dents', position: [-3, 0.32, 5.0], radius: 1.4, meshGroups: ['gutters'], severity: 'moderate', damageType: 'dent', facing: 'out', explanation: 'Top face and front face are documented separately — note type, size, and linear footage.' },
      { id: 'fs-gable', label: 'Gable end siding damage', position: [10, 1.6, 4], radius: 1.5, meshGroups: ['gable_ends'], severity: 'moderate', damageType: 'crack', facing: 'out', explanation: 'High on the elevation and easily missed from the ground — often triggers the matching question.' },
    ],
  },
  scopeSheet: {
    prompt: 'You documented hail damage across the storm-facing elevations. Build the exterior scope — select only the supported line items.',
    items: [
      { id: 's-siding', category: 'Elevations', label: 'Replace vinyl siding — storm-facing elevations', correct: true, note: 'Cracked courses documented on the storm-facing walls — replaced like kind and quality.' },
      { id: 's-matching', category: 'Elevations', label: 'Extend siding replacement for matching / line of sight', correct: true, note: 'Valid only where damaged siding cannot be matched within a line of sight and the policy plus state matching statute support it. Document the matching limitation before extending the scope.' },
      { id: 's-gable', category: 'Elevations', label: 'Replace gable-end siding', correct: true, note: 'Gable-end damage is documented and scoped the same as wall siding.' },
      { id: 's-fascia', category: 'Trim & Drainage', label: 'Replace aluminum fascia — by linear foot', correct: true, note: 'Soft metal, documented dents — a separate line item from soffit and gutters.' },
      { id: 's-soffit', category: 'Trim & Drainage', label: 'Replace soffit panels — damaged runs', correct: true, note: 'Soffit panels cracked / punctured by angled hail — separate from the fascia line item.' },
      { id: 's-gutters', category: 'Trim & Drainage', label: 'Replace gutters & downspouts — by linear foot', correct: true, note: 'Top and front face dents documented across the run; downspouts are separate items by size.' },
      { id: 's-stone', category: 'Do Not Include', label: 'Replace stone veneer wainscot', correct: false, note: 'Masonry shows spatter, not functional hail damage. Document the spatter as storm evidence — do not scope a veneer replacement from it.' },
      { id: 's-repaint', category: 'Do Not Include', label: 'Power wash & repaint the entire exterior', correct: false, note: 'Cleaning and repainting undamaged surfaces is maintenance, not hail repair.' },
      { id: 's-wrap', category: 'Do Not Include', label: 'Replace house wrap behind all siding', correct: false, note: 'The WRB is only scoped where siding is removed and the wrap is actually compromised — not as a default.' },
    ],
  },
  glossary: pickGlossary(
    ['spatter', 'functional-vs-cosmetic', 'matching', 'directional-damage', 'detach-reset', 'collateral-damage', 'line-item', 'op'],
    'Lock in the terminology behind a siding-and-exterior hail scope.',
  ),
}

// ════════════════════════════════════════════════════════════════════════════════
// RESIDENTIAL HAIL — Scenario 4: Mechanicals & Site
// ════════════════════════════════════════════════════════════════════════════════

export const HAIL_MECHANICALS_SITE: DamageScenario = {
  id: 'hail-mechanicals-site',
  title: 'Residential Hail: Mechanicals & Site',
  subtitle: 'The components inspections forget — AC condenser, chimney chase, downspouts, and roof penetrations',
  visibleGroups: ['rooftop_hvac', 'chimney', 'gutters', 'soft_metals', 'sheathing', 'garage_roof', 'fascia_soffit', 'site_elements'],
  annotations: [
    {
      id: 'hm-1',
      position: [-10.3, -1.6, 0],
      damageType: 'crushed',
      facing: [-1, 0, 0],
      markScale: 0.85,
      title: 'Crushed condenser fins',
      description: 'Aluminum condenser fins crush from hail impact, restricting airflow and forcing the unit to work harder. Document the percentage of fin area damaged — it determines whether the fins are combed (repair) or the unit is replaced.',
      severity: 'severe',
      indicator: 'circle',
      radius: 0.3,
    },
    {
      id: 'hm-2',
      position: [-9.5, -1.0, 0],
      damageType: 'dent',
      facing: 'up',
      markScale: 0.9,
      title: 'Condenser cabinet & top',
      description: 'The sheet-metal cabinet, top grille, and louvers dent from hail. Photograph the nameplate for model, serial, and tonnage — that drives the replacement pricing if the fin damage exceeds the repair threshold.',
      severity: 'moderate',
      indicator: 'circle',
      radius: 0.3,
    },
    {
      id: 'hm-3',
      position: [7, 4.75, 0],
      damageType: 'dent',
      facing: 'up',
      title: 'Chimney chase cover / crown',
      description: 'The metal chase cover or crown on top of the chimney is soft metal and dents readily. The masonry chimney itself does not take functional hail damage — only the metal cover, cap, and flashing do.',
      severity: 'moderate',
      indicator: 'circle',
      radius: 0.35,
    },
    {
      id: 'hm-4',
      position: [7.4, -2.15, 4.9],
      damageType: 'dent',
      facing: 'out',
      title: 'Downspout dents',
      description: 'Downspouts are soft metal and dent on the exposed faces. They are documented separately from the gutter run, by size and linear footage. Easily missed because inspections stop at the gutter.',
      severity: 'minor',
      indicator: 'circle',
      radius: 0.3,
    },
    {
      id: 'hm-5',
      position: [3, 3.4, -2],
      damageType: 'dent',
      facing: 'up',
      title: 'Roof penetration vents',
      description: 'Goosenecks, vent caps, and exhaust hoods are soft metal and dent clearly. They corroborate hail on the roof and each damaged unit is its own line item — frequently left off the scope.',
      severity: 'minor',
      indicator: 'circle',
      radius: 0.3,
    },
  ],
  stops: [
    {
      ...C([2, 9, 19], [-2, 0, 0], 48),
      title: 'The Components Inspections Forget',
      narration: 'Most inspections stop at the roof and the elevations. The mechanicals and site components — the AC condenser, the chimney chase, the downspouts, the roof penetrations — are where the most line items get left off the scope. Walk the property like the storm did: top to bottom, every exposed component.',
      annotationIds: [],
      highlightedGroups: ['rooftop_hvac', 'chimney', 'gutters'],
    },
    {
      ...C([-15, 1, 5], [-10.3, -1.6, 0], 34),
      title: 'AC Condenser — Fins',
      narration: 'Hail crushes the aluminum condenser fins, restricting airflow. Photograph from the side that shows the damage pattern, with a ruler. Document the percentage of fin area damaged — typically more than 15 to 25 percent moves it from combing the fins (repair) to replacing the unit.',
      annotationIds: ['hm-1'],
      highlightedGroups: ['rooftop_hvac'],
    },
    {
      ...C([-13, 3, 6], [-9.5, -1.0, 0], 36),
      title: 'AC Condenser — Cabinet & Nameplate',
      narration: 'The sheet-metal cabinet, top grille, and louvers dent from hail. Get the nameplate — model, serial, tonnage — because that determines replacement pricing. The condenser is a major line item; the disconnect and the refrigerant lines are documented but rarely damaged by hail themselves.',
      annotationIds: ['hm-2'],
      highlightedGroups: ['rooftop_hvac'],
    },
    {
      ...C([12, 7, 9], [7, 4.75, 0], 34),
      title: 'Chimney Chase & Cap',
      narration: 'Inspect the metal chase cover, crown, and cap on top of the chimney — all soft metal that dents readily. The masonry chimney itself does not take functional hail damage. Scope the metal components; do not scope a masonry rebuild from hail.',
      annotationIds: ['hm-3'],
      highlightedGroups: ['chimney'],
    },
    {
      ...C([11, 0, 11], [7.4, -2.15, 4.9], 36),
      title: 'Downspouts',
      narration: 'Downspouts are soft metal and dent on the exposed faces — documented separately from the gutter run by size and linear footage. Walk every elbow and bracket location; impacts concentrate where the downspout sits proud of the wall.',
      annotationIds: ['hm-4'],
      highlightedGroups: ['gutters'],
    },
    {
      ...C([5, 8, -8], [3, 3.4, -2], 32),
      title: 'Roof Penetration Vents',
      narration: 'Goosenecks, turbine vents, and exhaust caps stand proud of the roof and take direct hail impact — they corroborate the storm even when the field shingles read ambiguously. Each damaged unit is its own line item, and these are the items most often forgotten.',
      annotationIds: ['hm-5'],
      highlightedGroups: ['soft_metals'],
    },
    {
      ...C([4, 10, 18], [-1, 1, 0], 48),
      title: 'Completing the Evidence Chain',
      narration: 'Dented condenser fins, a dented chimney chase, dented downspouts, dented roof vents — all with consistent round impacts matching the storm report — complete the evidence chain and support the roof and elevation findings. Document the mechanicals and site components, or you under-scope the claim.',
      annotationIds: ['hm-1', 'hm-2', 'hm-3', 'hm-4', 'hm-5'],
      highlightedGroups: ['rooftop_hvac', 'chimney', 'gutters', 'soft_metals'],
    },
  ],
  findChallenge: {
    prompt: 'Inspect the components inspections forget. Click each documentable piece of hail damage on the mechanicals and site components.',
    startView: { position: [1, 8, 17], target: [-2, 0, 0], fov: 44 },
    targets: [
      { id: 'fm-fins', label: 'Crushed condenser fins', position: [-10.3, -1.6, 0], radius: 1.2, meshGroups: ['rooftop_hvac'], severity: 'severe', damageType: 'crushed', facing: [-1, 0, 0], markScale: 0.85, explanation: 'Percentage of fin area damaged decides combing (repair) vs. unit replacement.' },
      { id: 'fm-cabinet', label: 'Dented condenser cabinet', position: [-9.5, -1.0, 0], radius: 1.2, meshGroups: ['rooftop_hvac'], severity: 'moderate', damageType: 'dent', facing: 'up', markScale: 0.9, explanation: 'Cabinet, top grille, and louvers dent — get the nameplate for replacement pricing.' },
      { id: 'fm-chimney', label: 'Dented chimney chase / cap', position: [7, 4.75, 0], radius: 1.6, meshGroups: ['chimney'], severity: 'moderate', damageType: 'dent', facing: 'up', explanation: 'The metal chase cover and cap dent — the masonry itself does not take functional hail damage.' },
      { id: 'fm-downspout', label: 'Dented downspout', position: [7.4, -2.15, 4.9], radius: 1.5, meshGroups: ['gutters'], severity: 'minor', damageType: 'dent', facing: 'out', explanation: 'Documented separately from the gutter run, by size and linear footage.' },
      { id: 'fm-vents', label: 'Dented roof penetration vent', position: [3, 3.4, -2], radius: 1.2, meshGroups: ['soft_metals'], severity: 'minor', damageType: 'dent', facing: 'up', explanation: 'Goosenecks and vent caps corroborate the storm — each is its own line item.' },
    ],
  },
  scopeSheet: {
    prompt: 'You documented hail damage to the mechanicals and site components. The condenser fin damage exceeds the repair threshold. Build the scope — select only the supported line items.',
    items: [
      { id: 'm-condenser', category: 'HVAC', label: 'Replace AC condenser unit — fin damage exceeds repair threshold', correct: true, note: 'Documented fin damage is severe (over the 15–25% threshold). Price from the nameplate model and tonnage.' },
      { id: 'm-cabinet', category: 'HVAC', label: 'Replace condenser cabinet top grille / louvers', correct: true, note: 'Sheet-metal cabinet components are dented and documented — included where the unit is not fully replaced, or as part of the replacement.' },
      { id: 'm-comb', category: 'HVAC', label: 'Comb / straighten condenser fins', correct: false, note: 'Fin combing is only appropriate for minor damage (under the 15–25% threshold). The documented damage here is severe — the unit is replaced.' },
      { id: 'm-chase', category: 'Chimney & Drainage', label: 'Replace chimney chase cover / crown — dented', correct: true, note: 'The metal chase cover is soft metal and is documented dented — a separate line item.' },
      { id: 'm-downspout', category: 'Chimney & Drainage', label: 'Replace / repair downspouts — by size', correct: true, note: 'Downspouts are documented separately from the gutter run, by size and linear footage.' },
      { id: 'm-vents', category: 'Chimney & Drainage', label: 'Replace dented roof penetration vents', correct: true, note: 'Goosenecks and vent caps are documented dented — each damaged unit is its own line item.' },
      { id: 'm-rebuild', category: 'Do Not Include', label: 'Rebuild masonry chimney', correct: false, note: 'Hail does not cause functional damage to masonry. Scope only the metal chase cover, cap, and flashing.' },
      { id: 'm-ductwork', category: 'Do Not Include', label: 'Replace HVAC ductwork', correct: false, note: 'Ductwork is interior and not hail-exposed. No damage was documented.' },
      { id: 'm-driveway', category: 'Do Not Include', label: 'Replace concrete driveway', correct: false, note: 'Hail does not cause functional damage to a concrete driveway. Not a supported line item.' },
    ],
  },
  glossary: pickGlossary(
    ['soft-metals', 'functional-vs-cosmetic', 'collateral-damage', 'line-item', 'directional-damage', 'supplement', 'acv-rcv', 'recoverable-depreciation'],
    'Lock in the terminology behind a mechanicals-and-site hail scope.',
  ),
}

// ════════════════════════════════════════════════════════════════════════════════
// NON-HAIL DIAGNOSTIC SCENARIOS (walkthrough-only — regression canaries)
// ════════════════════════════════════════════════════════════════════════════════

export const ROOF_BLISTERING: DamageScenario = {
  id: 'roof-blistering',
  title: 'Shingle Blistering vs. Hail',
  subtitle: 'Tell asphalt-shingle blisters and weathering apart from real hail damage — the diagnostic that decides the claim',
  visibleGroups: ['walls_1st', 'walls_2nd', 'gable_ends', 'sheathing', 'ridge_cap', 'valley_metal', 'chimney', 'soft_metals', 'fascia_soffit', 'gutters', 'dormer', 'turret', 'bump_roof', 'garage_roof'],
  annotations: [
    {
      id: 'rb-1',
      position: [1, 2.45, 2],
      title: 'Thermal blister (intact granules)',
      description: 'Asphalt-shingle blisters form when volatile gases or trapped moisture in the asphalt expand under solar heat. They are ROUND, RAISED, and the granule surface on top is intact — no fracture, no granule loss, no exposed mat. Press gently; blisters often feel slightly soft. Diagnostic rule: raised + intact = blister, never hail.',
      severity: 'moderate',
      indicator: 'area',
      radius: 0.5,
      damageType: 'blister',
      facing: 'roof-front',
    },
    {
      id: 'rb-2',
      position: [-3, 2.11, 2.5],
      title: 'Open blister (ruptured — pre-existing)',
      description: 'When a blister ruptures, the cap layer peels away and the asphalt mat is exposed. This is a maintenance defect — it happens over months or years of thermal cycling, never from a single storm. If you scope a ruptured blister as hail, the carrier denies the claim and your inspection loses credibility. Document it separately as a pre-existing condition.',
      severity: 'severe',
      indicator: 'circle',
      radius: 0.3,
      damageType: 'blister',
      facing: 'roof-front',
    },
    {
      id: 'rb-3',
      position: [4, 3.11, 1],
      title: 'Hail bruise (for comparison)',
      description: 'A hail bruise is the OPPOSITE of a blister: FLAT or slightly concave, with fractured granules and exposed mat in a round pattern matching the hailstone diameter. The chalk test reveals the fracture line where granules are loose. Bruise sizes are CONSISTENT across the roof; blisters vary at random.',
      severity: 'severe',
      codeRef: 'HAAG Engineering — Hail Damage to Composition Roofs',
      indicator: 'circle',
      radius: 0.2,
      damageType: 'hail-bruise',
      facing: 'roof-front',
    },
    {
      id: 'rb-4',
      position: [-2, 2.45, -2],
      title: 'Alligatoring / surface checking (aged)',
      description: 'On a heavily-weathered asphalt roof the binder loses oil and the surface develops a network of fine cracks — surface checking, sometimes called alligatoring. It indicates end-of-life UV degradation and is NEVER storm damage. An aged roof may still take real hail damage; the test is whether bruises are flat with fractured granules, not whether the field looks cracked.',
      severity: 'moderate',
      indicator: 'area',
      radius: 0.4,
      damageType: 'alligator',
      facing: 'roof-back',
    },
    {
      id: 'rb-5',
      position: [3, 1.78, -3],
      title: 'Granule loss pattern (mechanical)',
      description: 'Granule loss from foot traffic, wind-driven rain, or normal weathering is gradual and uniform — concentrated in walking paths and along eaves where runoff scours. Storm-related granule loss is concentrated in ROUND impact zones matching the hailstone diameter. Document the pattern: uniform sweep = mechanical, round clusters = storm.',
      severity: 'minor',
      indicator: 'area',
      radius: 0.5,
      damageType: 'spatter',
      facing: 'roof-back',
    },
  ],
  stops: [
    {
      ...C([10, 9, 14], [0, 2.5, 0], 44),
      title: 'Roof Overview — Before Getting Close',
      narration: 'Before you climb on the roof, walk the perimeter and read the slopes. Are there visible blistered patches, dark scour lines, or weathered streaks? Identify the storm-facing slope and the ridge orientation. These landmarks tell you where to start your test squares before you touch a single shingle.',
      annotationIds: [],
      highlightedGroups: ['sheathing'],
    },
    {
      ...C([3, 6, 9], [0, 2.2, 2], 34),
      title: 'Getting Closer — What You See',
      narration: 'On approach, you should already see the distinction: round raised bumps with intact granules are blisters. Flat darker spots with exposed mat are hail bruises. The most common adjuster mistake is calling blisters as hail bruises — that gets the claim denied and damages your credibility. Slow down and look BEFORE you photograph.',
      annotationIds: ['rb-1', 'rb-2'],
      highlightedGroups: ['sheathing'],
    },
    {
      ...C([2, 4, 5], [1, 2.45, 2], 24),
      title: 'Thermal Blister — Close Up',
      narration: 'A thermal blister is RAISED like a small dome. The granule surface on top is smooth and INTACT — no fracture, no exposed mat. Blisters vary from a quarter-inch to several inches and appear at random across the slope. Press gently — a fresh blister may feel slightly soft. Never puncture one to test it; that creates the damage you came to deny.',
      annotationIds: ['rb-1'],
      highlightedGroups: ['sheathing'],
    },
    {
      ...C([6, 5, 5], [4, 3.11, 1], 24),
      title: 'Hail Bruise — The Difference',
      narration: 'This is the opposite read. A hail bruise is FLAT or slightly concave. The granule surface is fractured in a round pattern that matches the hailstone diameter. Rub chalk across the spot — the chalk catches differently on the fractured zone than on the intact granules around it. Bruise sizes are CONSISTENT across the roof; blisters are not.',
      annotationIds: ['rb-3'],
      highlightedGroups: ['sheathing'],
    },
    {
      ...C([-1, 4, 7], [-3, 2.11, 2.5], 26),
      title: 'Ruptured Blister — Pre-Existing',
      narration: 'A ruptured blister exposes the asphalt mat where the cap layer peeled off. This is ALWAYS pre-existing — thermal cycling, not a storm event. If a ruptured blister gets mixed into your hail scope, the carrier sees it and the entire claim loses credibility. Document ruptured blisters separately and label them as pre-existing.',
      annotationIds: ['rb-2'],
      highlightedGroups: ['sheathing'],
    },
    {
      ...C([-5, 5, -7], [-2, 2.45, -2], 28),
      title: 'Alligatoring — Age Indicator',
      narration: 'On the back slope: the field has surface checks running in a network pattern. That is UV breakdown — the asphalt binder dried out over years of sun. Alligatoring is never storm damage. However, an aged roof can still take real hail damage; the diagnostic remains whether bruises are flat with fractured granules, not whether the field looks cracked.',
      annotationIds: ['rb-4'],
      highlightedGroups: ['sheathing'],
    },
    {
      ...C([4, 5, -8], [3, 1.78, -3], 28),
      title: 'Granule Loss — Pattern Tells the Story',
      narration: 'Granule loss from traffic and weathering sweeps uniformly along the slope, concentrated in walking paths and near eaves where runoff scours. Storm-related granule loss is concentrated in ROUND clusters that match hailstone size. The PATTERN is the diagnostic — uniform sweep is mechanical, round clusters are storm.',
      annotationIds: ['rb-5'],
      highlightedGroups: ['sheathing'],
    },
    {
      ...C([12, 11, 14], [0, 2.5, 0], 46),
      title: 'Documentation Standard',
      narration: 'When you scope a roof with both blisters and hail: (1) photograph blisters and label them pre-existing in your report; (2) chalk-test and photograph at least three test squares on the storm-facing slope; (3) document soft metals for independent hail confirmation; (4) note the roof age and overall condition. The carrier expects you to separate the two — if you do not, the claim is denied in full.',
      annotationIds: ['rb-1', 'rb-2', 'rb-3', 'rb-4', 'rb-5'],
      highlightedGroups: ['sheathing', 'soft_metals'],
    },
  ],
}

export const SOFT_METAL_DAMAGE: DamageScenario = {
  id: 'soft-metal-damage',
  title: 'Soft Metal Hail Indicators',
  subtitle: 'Soft metals prove hail contact at the property — learn to find and document them on a real residence',
  visibleGroups: ['walls_1st', 'walls_2nd', 'gable_ends', 'sheathing', 'ridge_cap', 'soft_metals', 'rooftop_hvac', 'gutters', 'fascia_soffit', 'chimney', 'dormer', 'turret', 'bump_roof', 'garage_roof'],
  annotations: [
    {
      id: 'sm-1',
      position: [-2, 3.4, -1],
      title: 'Turbine vent — dome dents',
      description: 'Aluminum turbine vents dent easily from hail. Round dents on the dome (top) and throat (cylindrical body) confirm hail contact. The dent pattern should be consistent with the storm direction. Note whether the vent still spins freely — a seized turbine from hail impact is a replacement, not a repair, and is its own line item.',
      severity: 'moderate',
      indicator: 'circle',
      radius: 0.3,
      damageType: 'dent',
      facing: 'up',
    },
    {
      id: 'sm-2',
      position: [-4, 3.2, 0.5],
      title: 'Pipe boot — lead flashing',
      description: 'Lead pipe boots are the softest metal on a roof — they show dents from even one-inch hail. Inspect the lead flashing for round dents and the neoprene collar for UV-cracking accelerated by impact. Each pipe boot is its own line item; a failed collar is also secondary water-intrusion exposure around the penetration.',
      severity: 'moderate',
      indicator: 'circle',
      radius: 0.2,
      damageType: 'dent',
      facing: 'up',
    },
    {
      id: 'sm-3',
      position: [-10.3, -1.6, 0],
      title: 'Condenser fins — crushed',
      description: 'Aluminum condenser fins crush from hail impact and restrict airflow across the coil. Document the PERCENTAGE of fin area damaged — typically >15–25% drives unit replacement rather than fin combing (repair). Get the nameplate for model, serial, and tonnage before you scope the line item.',
      severity: 'severe',
      indicator: 'circle',
      radius: 0.5,
      damageType: 'crushed',
      facing: [-1, 0, 0],
      markScale: 0.85,
    },
    {
      id: 'sm-4',
      position: [0, 0.4, 5.05],
      title: 'Gutter top face',
      description: 'Hail dents the horizontal (top) face and vertical (front) face of gutters — those are TWO separate line items, not one. Walk the full gutter run with your ruler. Document type (K-style, half-round), material (aluminum, steel, copper), size (5-inch, 6-inch), and total linear footage. Downspouts are separate items by size.',
      severity: 'moderate',
      indicator: 'circle',
      radius: 0.3,
      damageType: 'dent',
      facing: 'up',
    },
  ],
  stops: [
    {
      ...C([8, 10, 14], [0, 1.5, 0], 44),
      title: 'Why Soft Metals Matter',
      narration: 'Soft metals are your PROOF of hail at the property. Even when shingle bruises are subtle, round dents in aluminum and lead are unmistakable. Carriers cannot dispute them when they match the storm report for direction and stone size. Always document soft metals first — they establish hail contact before you ever pull a test square on the field.',
      annotationIds: [],
      highlightedGroups: ['soft_metals', 'rooftop_hvac', 'gutters'],
    },
    {
      ...C([-5, 6, -6], [-2, 3.35, -1], 28),
      title: 'Turbine Vent — Back Slope',
      narration: 'Walk to the back slope. The turbine vent is aluminum and reads hail damage clearly — round dents on the dome and throat. Document each dent with a ruler for scale and note whether the turbine still spins. A seized turbine is a replacement line item, not a repair. The dent pattern should be consistent in size with the storm-direction stones.',
      annotationIds: ['sm-1'],
      highlightedGroups: ['soft_metals'],
    },
    {
      ...C([-2, 5, 6], [-4, 3.1, 0.5], 24),
      title: 'Pipe Boot — Close-Up',
      narration: 'Lead pipe boots are the softest metal on any roof. They show dents from even one-inch hail. Inspect the lead flashing for round dents and the neoprene collar for cracks. A cracked collar allows water intrusion around the penetration — a secondary exposure that runs with the storm event even when the crack itself is UV-aided.',
      annotationIds: ['sm-2'],
      highlightedGroups: ['soft_metals'],
    },
    {
      ...C([-14, 1, 4], [-10.3, -1.6, 0], 28),
      title: 'HVAC Condenser — Crushed Fins',
      narration: 'Step off the roof to the ground-level condenser beside the garage. Hail crushes the aluminum fins on the storm-facing sides. Photograph each face that shows damage and use your ruler. Document the percentage of total fin area damaged — typically >15–25% means unit replacement rather than fin combing. Pull the nameplate for model, serial, and tonnage before you write the scope.',
      annotationIds: ['sm-3'],
      highlightedGroups: ['rooftop_hvac'],
    },
    {
      ...C([3, 3, 11], [0, 0.4, 5.0], 30),
      title: 'Gutter Damage — Two Line Items',
      narration: 'Gutters are often overlooked. Hail hits the TOP face (horizontal) and the FRONT face (vertical) — each is a separate line item, not one. Walk the full run with your ruler. Document type (K-style, half-round), material (aluminum, steel, copper), size (5-inch, 6-inch), and total linear footage. Downspouts are separate items by size.',
      annotationIds: ['sm-4'],
      highlightedGroups: ['gutters', 'fascia_soffit'],
    },
    {
      ...C([12, 11, 14], [-1, 1, 0], 44),
      title: 'Building Your Evidence Chain',
      narration: 'Soft metals build an evidence chain: dented turbine, dented pipe boot, crushed condenser fins, dented gutters — all with consistent round impacts matching the storm report. With that chain in place the carrier cannot deny hail contact at the property, and your test-square findings on the field stand on solid ground. Document soft metals BEFORE you touch the field shingles.',
      annotationIds: ['sm-1', 'sm-2', 'sm-3', 'sm-4'],
      highlightedGroups: ['soft_metals', 'rooftop_hvac', 'gutters'],
    },
  ],
}

// ── All scenarios — residential hail set first ──

export const ALL_DAMAGE_SCENARIOS: DamageScenario[] = [
  HAIL_ROOF_RESIDENTIAL,
  HAIL_WINDOWS_DOORS,
  HAIL_SIDING_EXTERIOR,
  HAIL_MECHANICALS_SITE,
  ROOF_BLISTERING,
  SOFT_METAL_DAMAGE,
]

export function getDamageScenario(id: string): DamageScenario | undefined {
  return ALL_DAMAGE_SCENARIOS.find(s => s.id === id)
}
