"""PDF report generation using WeasyPrint."""
import io
import uuid
from datetime import datetime

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.report import Report, ReportItem
from app.models.project import Project
from app.models.media import Media
from app.services.storage_service import get_s3_client, get_public_url, get_settings


REPORT_HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<style>
  @page {{ size: letter; margin: 1in; }}
  body {{ font-family: Helvetica, Arial, sans-serif; color: #1e293b; font-size: 11pt; }}
  .cover {{ text-align: center; padding-top: 3in; }}
  .cover h1 {{ font-size: 28pt; color: #2563eb; margin-bottom: 0.5em; }}
  .cover .subtitle {{ font-size: 14pt; color: #64748b; }}
  .cover .meta {{ margin-top: 2em; font-size: 10pt; color: #94a3b8; }}
  .section {{ margin-top: 1.5em; }}
  .section h2 {{ font-size: 14pt; color: #0f172a; border-bottom: 2px solid #e2e8f0; padding-bottom: 4px; }}
  .info-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 8px; margin-top: 0.5em; }}
  .info-item {{ font-size: 9pt; }}
  .info-label {{ color: #94a3b8; }}
  .media-item {{ margin-top: 1em; page-break-inside: avoid; }}
  .media-item img {{ max-width: 100%; border-radius: 4px; }}
  .media-caption {{ font-size: 9pt; color: #64748b; margin-top: 4px; }}
  .note-block {{ background: #f8fafc; border-left: 3px solid #2563eb; padding: 12px; margin-top: 1em; font-size: 10pt; }}
  .footer {{ position: fixed; bottom: 0.5in; left: 1in; right: 1in; text-align: center; font-size: 8pt; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 4px; }}
  .page-break {{ page-break-before: always; }}
</style>
</head>
<body>
  {content}
  <div class="footer">Generated by fieldcam.app &middot; {generated_date}</div>
</body>
</html>
"""


async def generate_report_pdf(db: AsyncSession, report_id: str) -> str:
    """Generate PDF for a report and upload to storage. Returns storage key."""
    from weasyprint import HTML

    report_result = await db.execute(select(Report).where(Report.id == uuid.UUID(report_id)))
    report = report_result.scalar_one()

    project_result = await db.execute(select(Project).where(Project.id == report.project_id))
    project = project_result.scalar_one()

    # Build HTML content
    content_parts = []

    # Cover page
    address = ", ".join(filter(None, [project.address_line_1, project.city, project.state, project.postal_code]))
    content_parts.append(f"""
    <div class="cover">
        <h1>{report.title}</h1>
        <div class="subtitle">{project.name}</div>
        <div class="meta">
            {f'<div>{address}</div>' if address else ''}
            {f'<div>Claim: {project.claim_number}</div>' if project.claim_number else ''}
            <div>Generated: {datetime.utcnow().strftime('%B %d, %Y')}</div>
        </div>
    </div>
    """)

    # Project info section
    content_parts.append('<div class="page-break"></div>')
    content_parts.append('<div class="section"><h2>Project Information</h2>')
    content_parts.append('<div class="info-grid">')
    info_fields = [
        ("Project", project.name),
        ("Number", project.project_number),
        ("Customer", project.customer_name),
        ("Address", address),
        ("Claim", project.claim_number),
        ("Carrier", project.carrier_reference),
        ("Damage", project.damage_category),
        ("Inspection", project.inspection_type),
    ]
    for label, value in info_fields:
        if value:
            content_parts.append(f'<div class="info-item"><span class="info-label">{label}:</span> {value}</div>')
    content_parts.append('</div></div>')

    # Report items
    settings = get_settings()
    for item in sorted(report.items, key=lambda x: x.sort_order):
        if item.page_break_before:
            content_parts.append('<div class="page-break"></div>')

        if item.media_id:
            media_result = await db.execute(select(Media).where(Media.id == item.media_id))
            media = media_result.scalar_one_or_none()
            if media:
                img_url = f"{settings.storage_endpoint}/{settings.storage_bucket}/{media.preview_key or media.storage_key}"
                caption_parts = [media.original_filename or ""]
                if media.room_label:
                    caption_parts.append(f"Room: {media.room_label}")
                if media.captured_at:
                    caption_parts.append(media.captured_at.strftime("%m/%d/%Y %H:%M"))
                caption = " &middot; ".join(filter(None, caption_parts))

                content_parts.append(f"""
                <div class="media-item">
                    <img src="{img_url}" />
                    <div class="media-caption">{caption}</div>
                </div>
                """)

        if item.note_text:
            content_parts.append(f'<div class="note-block">{item.note_text}</div>')

    html_content = REPORT_HTML_TEMPLATE.format(
        content="\n".join(content_parts),
        generated_date=datetime.utcnow().strftime("%B %d, %Y at %H:%M UTC"),
    )

    # Generate PDF
    pdf_bytes = HTML(string=html_content).write_pdf()

    # Upload to storage
    storage_key = f"{report.company_id}/reports/{report.id}.pdf"
    client = get_s3_client()
    client.put_object(
        Bucket=settings.storage_bucket,
        Key=storage_key,
        Body=pdf_bytes,
        ContentType="application/pdf",
    )

    # Update report
    report.pdf_storage_key = storage_key
    report.status = "ready"
    await db.flush()

    return storage_key
